GET http://127.0.0.1:5000/monitoring/attendance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJyb2xlIjoibW9uaXRvcmluZ19vZmZpY2VyIiwiaWF0IjoxNzc3NzA3Njg4LCJleHAiOjE3Nzc3MTEyODgsInR5cGUiOiJtb25pdG9yaW5nIn0.8nu3gv1VX9JFN7cJzLxqSF6KsND0L8HBmdMKYPqAWPg